### ISSUE TITLE
Hey, are you still there?

### ISSUE THREAD

**Issue by DerDevHD** [wjtje/2048-fx-cg-10-20-50#6]
Hey! I just want to know, if you are still active, because I would like to meet up in discord, I have some questions.
I don't want to bother you, if you don't want to talk to me, you can just delete, close or ignore this issue.

Best regards!

**Comment by wjtje** [comment]
Yes, I am still here, but I am no longer working on this project. 
If you have any questions you can contact me on discord (WJTJE#7243).
